create table country(
                        id bigint generated by default as identity primary key,
                        name varchar(255),
                        continent varchar(255)
);
create table author(
                       id bigint generated by default as identity primary key,
                       name varchar(255),
                       surname varchar(255),
                       country_id bigint references country
);
create table book(
                     id bigint generated by default as identity primary key,
                     name varchar(255),
                     state boolean,
                     category varchar(50),
                     author_id bigint references author,
                     availableCopies integer,
);
create table related_books(
                              book_id bigint references book,
                              related_book_id bigint references book,
                              primary key (book_id, related_book_id)
);
create table book_users
(
    username varchar(255) primary key,
    password varchar(255),
    name varchar(255),
    surname varchar(255),
    is_account_non_expired boolean default true,
    is_account_non_locked boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled boolean default true,
    role varchar(50)
);
create table wishlist_books (
                                user_username varchar(255) references book_users,
                                book_id bigint references book,
                                primary key (user_username, book_id)
);